# General
set -g mouse on
set -g base-index 1
set -g renumber-windows on
set -g status-position top
set -g allow-passthrough on
set -g repeat-time 1000
set -g mode-keys vi
set -g pane-border-lines heavy
set -as terminal-features ",xterm-256color:RGB"

# Key Bindings
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -r n next-window
bind -r p previous-window
bind m set -g mouse \; display-message "Mouse #{?mouse,on,off}"
bind g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E
bind S if-shell -F "#{@ms}" \
  "set-option -wu @ms \; set-option -wu monitor-silence \; display-message 'Monitor silence: off'" \
  "set-option -w @ms 1 \; set-option -w monitor-silence 15 \; display-message 'Monitor silence: 15s'"
bind W run-shell "~/.tmux-themes/set-wl.sh"
bind A set-window-option automatic-rename on \; display-message "Auto-rename: on"

# Vi Copy Mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel

# Pane Resizing
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Plugin Settings
set -g @continuum-restore 'on'

# Hooks
set-hook -g pane-focus-in 'run-shell "~/.tmux-themes/set-wl.sh"'
set-hook -g after-select-window 'run-shell "~/.tmux-themes/set-wl.sh"'

# Theme
source-file ~/.tmux-themes/terminal.tmuxtheme

# Initialize TMUX plugin manager (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
