# General
set -g mouse on
set -g base-index 1
set -as terminal-features ",xterm-256color:RGB"
set -g renumber-windows on
set -g status-position bottom
set -g allow-passthrough on
set -g repeat-time 1000
set -g mode-keys vi

# Key Bindings
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -r n next-window
bind -r p previous-window
bind m set -g mouse \; display-message "Mouse #{?mouse,on,off}"

# Pane Resizing
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Theme
set -g @themepack 'powerline/default/cyan'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
