# General
set -g mouse on
set -g base-index 1
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g renumber-windows on
set -g status-position top
set -g history-limit 50000
set -g escape-time 0
set -g mode-keys vi
set -g display-time 3000

# Key Bindings
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
bind | split-window -h
bind - split-window -v

# Pane Resizing
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'

# Plugin Settings
set -g @themepack 'powerline/default/cyan'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
