model_provider = "amazon-bedrock"
model = "openai.gpt-5.6-terra"
model_reasoning_effort = "high"

[projects."/"]
trust_level = "trusted"

[projects."/home/michaelco/git/depot.git"]
trust_level = "trusted"

[projects."/home/michaelco/git"]
trust_level = "trusted"

[projects."/Users/michaelco/dotfiles"]
trust_level = "trusted"

[tui]
theme = "ansi"
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-remaining"]
status_line_use_colors = true

[tui.model_availability_nux]
"openai.gpt-5.5" = 1

[features]
hooks = true

[hooks.state]

[hooks.state."worktrunk@worktrunk:plugin.json#hooks[0]:permission_request:0:0"]
trusted_hash = "sha256:b5f6112154fd814298da679652ea096e11434b7f2876d471eb00c790a68045d0"
enabled = true

[hooks.state."worktrunk@worktrunk:plugin.json#hooks[0]:user_prompt_submit:0:0"]
trusted_hash = "sha256:e2ffec558188fd0988ad51768594f675801fd2a1ba2895b5df2aca2650d70c2a"

[hooks.state."worktrunk@worktrunk:plugin.json#hooks[0]:stop:0:0"]
trusted_hash = "sha256:350c210fba4996f546f4d0483fc29286d73880ca5ef01fda3583ea2ce676945d"

[plugins."ex@personal"]
enabled = true

[plugins."worktrunk@worktrunk"]
enabled = true

[marketplaces.worktrunk]
last_updated = "2026-07-15T20:02:17Z"
last_revision = "df5c5d68e1b995b92086a218cf6b167e5f543c32"
source_type = "git"
source = "https://github.com/max-sixty/worktrunk.git"
